apiVersion: v1
kind: Service
metadata:
  name: employeeservice
  namespace: lab-generic
spec:
  type: NodePort
  selector:
    app: employeeservice
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
