apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqldb-pvc
  namespace: lab-generic
  labels:
    app: sqldb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
