apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldb
  namespace: lab-generic
  labels:
    app: sqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqldb
  template:
    metadata:
      labels:
        app: sqldb
    spec:
      containers:
        - name: sqldb
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "YourStrong!Passw0rd"
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: sqldb-pvc
