apiVersion: v1
kind: Service
metadata:
  name: sqldb
  namespace: lab-generic
  labels:
    app: sqldb
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
  selector:
    app: sqldb
